apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    name: weather-api
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: weather-api
