apiVersion: v1
kind: Service
metadata:
  name: service-tracker-ui
  labels:
    name: service-tracker-ui
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.deploy.containerPort}}
  selector:
    app: service-tracker-ui
